name: Build Android APK

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install buildozer==1.5.0 Cython==0.29.33 pillow
        
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          python3-pip \
          build-essential \
          git \
          python3 \
          python3-dev \
          ffmpeg \
          libsdl2-dev \
          libsdl2-image-dev \
          libsdl2-mixer-dev \
          libsdl2-ttf-dev \
          libportmidi-dev \
          libswscale-dev \
          libavformat-dev \
          libavcodec-dev \
          zlib1g-dev \
          openjdk-11-jdk
          
    - name: Link NDK
      run: |
        mkdir -p ~/.buildozer/android/platform
        ln -s /usr/local/lib/android/sdk/ndk/25.2.9519653 ~/.buildozer/android/platform/android-ndk-r25b
        export ANDROIDNDK=~/.buildozer/android/platform/android-ndk-r25b
        export ANDROIDNDKVER=r25b

    - name: Build with Buildozer
      run: |
        buildozer android debug
        
    - name: Save APK
      if: success()
      run: |
        mkdir -p apk-output
        cp bin/*.apk apk-output/
        
    - name: Upload APK directly
      if: success()
      uses: actions/upload-artifact@v2
      continue-on-error: true
      with:
        name: app-debug
        path: apk-output/*.apk

    - name: List APK (Alternative)
      if: always()
      run: |
        echo "=== APK Files (if any) ==="
        ls -la bin/ || echo "bin directory doesn't exist"
        find . -name "*.apk" -type f
